version: "3.7"

services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}_node"
    volumes:
      - ./public:/home/node/app
    restart: unless-stopped
    environment:
      - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN

networks:
  default:
    external:
      name: nginx-proxy
