version: "3.7"

services:
  node:
    build:
      context: ./public
      dockerfile: Dockerfile
    container_name: "${CONTAINER_NAME}_node"
    restart: unless-stopped
    environment:
      - NODE_ENV=$NODE_ENV
      - VIRTUAL_HOST=$VIRTUAL_HOST
      - LETSENCRYPT_HOST=$LETSENCRYPT_HOST
      - LETSENCRYPT_EMAIL=$LETSENCRYPT_EMAIL
      - KHALEESI_TELEGRAM_TOKEN=$KHALEESI_TELEGRAM_TOKEN
      - CHEEMS_TELEGRAM_TOKEN=$CHEEMS_TELEGRAM_TOKEN
      - DASHBOT_API_TOKEN=$DASHBOT_API_TOKEN
      - DEBUG_CHAT_ID=$DEBUG_CHAT_ID

networks:
  default:
    name: nginx-proxy
