name: Deploy to VPS
on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Deploy to VPS
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          # Deploy
          ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST << EOF
            # Ensure directory exists
            mkdir -p /opt/apps/$REPO_NAME
            cd /opt/apps/$REPO_NAME
          
            # Pull latest changes
            git pull || git clone https://github.com/${{ github.repository }}.git .
          
            # Set proper permissions for .env
            chmod 600 .env
          
            # Restart container
            docker-compose down
            docker-compose pull
            docker-compose up -d
          EOF